name: Create GitHub Release

on:
  push:
    tags:
      - 'v*' # runs on any v-prefixed tag like v1.0.1

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate release notes and create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
